export const FETCH_PAINTINGS_REQUEST = 'FETCH_PAINTINGS_REQUEST';
export const FETCH_PAINTINGS_SUCCESS = 'FETCH_PAINTINGS_SUCCESS';
export const FETCH_PAINTINGS_FAILURE = 'FETCH_PAINTINGS_FAILURE';

export const ADD_PAINTING_REQUEST = 'ADD_PAINTING_REQUEST';
export const ADD_PAINTING_SUCCESS = 'ADD_PAINTING_SUCCESS';
export const ADD_PAINTING_FAILURE = 'ADD_PAINTING_FAILURE';

export const DELETE_PAINTING_REQUEST = 'DELETE_PAINTING_REQUEST';
export const DELETE_PAINTING_SUCCESS = 'DELETE_PAINTING_SUCCESS';
export const DELETE_PAINTING_FAILURE = 'DELETE_PAINTING_FAILURE';

export const UPDATE_PAINTING_REQUEST = 'UPDATE_PAINTING_REQUEST';
export const UPDATE_PAINTING_SUCCESS = 'UPDATE_PAINTING_SUCCESS';
export const UPDATE_PAINTING_FAILURE = 'UPDATE_PAINTING_FAILURE';